# Generated by Django 3.1.7 on 2021-03-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('hint', models.CharField(max_length=400)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=100)),
                ('dname', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('mc', models.BooleanField()),
                ('lore', models.CharField(max_length=100)),
                ('cd', models.IntegerField()),
                ('components', models.CharField(max_length=100)),
                ('created', models.BooleanField()),
                ('charges', models.IntegerField()),
                ('attrib', models.JSONField()),
            ],
        ),
    ]
