# Generated by Django 3.1.7 on 2021-03-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='components',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
