# Generated by Django 3.1.7 on 2021-03-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210321_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='charges',
            field=models.CharField(max_length=10),
        ),
    ]
