# Generated by Django 3.1.7 on 2021-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210321_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mc',
            field=models.CharField(max_length=10),
        ),
    ]
